name: Checks

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          cache: "poetry"

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Run Install
        run: |
          poetry install

      - name: Run Lint
        run: |
          poetry run task lint

      - name: Run Tests
        run: |
          poetry run task test
