name: Checks

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Set up Python
        run: uv python install 3.12

      - name: Install dependencies
        run: |
          uv sync --all-extras --dev

      - name: Run Lint
        run: |
          uv run pylint --errors-only brightwheel_photos

      - name: Run Tests
        run: |
          uv run pytest