name: Checks

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Poetry
        run: pipx install poetry

      - uses: actions/setup-python@v5
        with:
          cache: poetry

      - name: Run Install
        run: |
          poetry install

      - name: Run Lint
        run: |
          poetry run task lint

      - name: Run Tests
        run: |
          poetry run task test
