name: Release
on:
  workflow_dispatch:
  release:
    types:
      - created

jobs:
  publish:
    environment: PyPI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: 3.8
          cache: poetry

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Publish
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          poetry config pypi-token.pypi $PYPI_TOKEN
          poetry publish --build
