name: Release
on:
  workflow_dispatch:
  release:
    types:
      - created

jobs:
  publish:
    environment: PyPI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: pipx install poetry

      - uses: actions/setup-python@v5
        with:
          cache: poetry

      - name: Publish
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          poetry config pypi-token.pypi $PYPI_TOKEN
          poetry publish --build
